
apiVersion: v1
kind: Service
metadata:
  name: coding-test-service
spec:
  selector:
    app: coding-test
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: coding-test
spec:
  selector:
    matchLabels:
      app: coding-test
  replicas: 1
  template:
    metadata:
      labels:
        app: coding-test
    spec:
      containers:
      - name: coding-test
        image: coding-test
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
      - name: etcd
        image: coding-test-etcd
        imagePullPolicy: IfNotPresent

